package rs.ac.uns.ftn.db.jdbc.statement;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import rs.ac.uns.ftn.db.jdbc.connection.ConnectionUtil_Basic;

public class Example03_QueryWithParams {

	public static void main(String[] args) {
		try (Connection connection = ConnectionUtil_Basic.getConnection();
				Statement statement = connection.createStatement();
				ResultSet resultSet = statement.executeQuery(generateQuery())) {
			
			if (!resultSet.isBeforeFirst()) {
				System.out.println("No data found"); // checks if the result generated by query is empty
			} else {
				System.out.printf("%-4s %s\n", "SPR", "NAZIV PROJEKTA");
				
				// iterating through result set
				while (resultSet.next()) {
					int spr = resultSet.getInt(1);
					String nap = resultSet.getString(2);
				
					System.out.printf("%-4d %s\n", spr, nap);
				}
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private static String generateQuery() {
		try (Scanner sc = new Scanner(System.in)) {
			System.out.println("MBR: ");
			String mbr = sc.nextLine();
			
			String query = "SELECT spr, nap FROM projekat\n"
					+ "WHERE spr IN (\n"
					+ "	SELECT spr FROM radproj\n"
					+ "	WHERE mbr = " + mbr
					+ ")";
			
			return query;
		}
	}
}
